stages:
  data_visualization:
    cmd: python src/data_visualization.py
    deps:
      - src/data_visualization.py
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
    outs:
      - docs/figures/target_distribution.png
      - docs/figures/correlation_heatmap_creditos.png
      - docs/figures/correlation_heatmap_tarjetas.png
      - docs/figures/ingresos_por_mora.png
      - docs/figures/ingresos_tasa_mora.png

  test_pandera:
    cmd: pytest --html=docs/report_pd.html --self-contained-html test/test_data_quality.py
    deps:
    - data/raw/datos_creditos.csv
    - data/raw/datos_tarjetas.csv
    - test/test_data_quality.py
    outs:
    - docs/report_pd.html

  test_ge:
    cmd: pytest --html=docs/report_ge.html --self-contained-html test/test_data_quality_ge.py
    deps:
    - data/raw/datos_creditos.csv
    - data/raw/datos_tarjetas.csv
    - test/test_data_quality_ge.py
    outs:
    - docs/report_ge.html